### ISSUE TITLE
Check the example , there should be a visual effect on input when hovering, typing in

### ISSUE THREAD

**Issue by heywhahappnd** [mysterious25/lesson0#4]

**Comment by heywhahappnd** [comment]
При неправильном вводе , он должен быть красным , посмотри пример.
Стрелка при нажатии, должна менять фон на зелёный

**Comment by mysterious25** [comment]
Можно стрелку уже не менять?Просто она у меня картинкой

**Comment by mysterious25** [comment]
а так при вводе не правильного - поправил
